site_name: Knut v4.0

theme:
  name: material
  palette:
    - scheme: kdab
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  logo: assets/transparentWhiteKDAB.svg

extra_css:
  - stylesheets/extra.css

use_directory_urls: false

repo_url: https://codereview.kdab.com/admin/repos/knut
repo_name: knut

nav:
    - Home: index.md
    - Getting Started:
        - Writing a script: getting-started/script.md
        - Command line interface: getting-started/cli.md
        - User interface: getting-started/gui.md
    - Contributing:
        - Getting started: contributing/getting-started.md
        - Architecture: contributing/architecture.md
        - Unit tests: contributing/unit-tests.md
    - Script API:
        - Script Module:
             - Argument: API/script/argument.md
             - CppClass: API/script/cppclass.md
             - CppDocument: API/script/cppdocument.md
             - CppFunction: API/script/cppfunction.md
             - Dir: API/script/dir.md
             - Document: API/script/document.md
             - File: API/script/file.md
             - FileInfo: API/script/fileinfo.md
             - LspDocument: API/script/lspdocument.md
             - Mark: API/script/mark.md
             - Message: API/script/message.md
             - Project: API/script/project.md
             - QDirValueType: API/script/qdirvaluetype.md
             - QFileInfoValueType: API/script/qfileinfovaluetype.md
             - Script: API/script/script.md
             - ScriptDialog: API/script/scriptdialog.md
             - Settings: API/script/settings.md
             - Symbol: API/script/symbol.md
             - TextDocument: API/script/textdocument.md
             - TextRange: API/script/textrange.md
             - UiDocument: API/script/uidocument.md
             - UiWidget: API/script/uiwidget.md
             - UserDialog: API/script/userdialog.md
             - Utils: API/script/utils.md
        - Script.Rc Module:
             - Action: API/script.rc/action.md
             - Asset: API/script.rc/asset.md
             - Menu: API/script.rc/menu.md
             - MenuItem: API/script.rc/menuitem.md
             - RcDocument: API/script.rc/rcdocument.md
             - Shortcut: API/script.rc/shortcut.md
             - String: API/script.rc/string.md
             - ToolBar: API/script.rc/toolbar.md
             - ToolBarItem: API/script.rc/toolbaritem.md
             - Widget: API/script.rc/widget.md
        - Script.Test Module:
             - TestCase: API/script.test/testcase.md
             - TestUtil: API/script.test/testutil.md

markdown_extensions:
    - toc:
        permalink: "#"
        toc_depth: 3
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.tabbed
    - attr_list

plugins:
    - search:
        separator: '[\s\-\.]+'
    - build_plantuml:
          render: "server"
          server: "http://www.plantuml.com/plantuml"
          output_format: "svg"
          diagram_root: "docs/assets"
          output_folder: "."
          input_folder: "."
          input_extensions: ""
