site_name: Knut v4.0

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

use_directory_urls: false

repo_url: https://codereview.kdab.com/admin/repos/knut
repo_name: knut

nav:
    - Home: index.md
    - Contributing: contributing.md
    - API:
        - Script Module:
             - Dir: API/script/dir.md
             - Document: API/script/document.md
             - File: API/script/file.md
             - FileInfo: API/script/fileinfo.md
             - Message: API/script/message.md
             - QDirValueType: API/script/qdirvaluetype.md
             - QFileInfoValueType: API/script/qfileinfovaluetype.md
             - Script: API/script/script.md
             - Settings: API/script/settings.md
             - TextDocument: API/script/textdocument.md
             - Utils: API/script/utils.md
        - Script.Test Module:
             - TestCase: API/script.test/testcase.md
             - TestUtil: API/script.test/testutil.md

markdown_extensions:
    - toc:
        permalink: "#"
        toc_depth: 3
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.tabbed
    - attr_list

plugins:
    - search:
        separator: '[\s\-\.]+'
