site_name: Knut v1.1

theme:
  name: material
  palette:
    - scheme: kdab
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  logo: assets/transparentWhiteKDAB.svg

extra_css:
  - stylesheets/extra.css

use_directory_urls: false

repo_url: https://codereview.kdab.com/admin/repos/knut
repo_name: knut

nav:
    - Home: index.md
    - Getting Started:
        - Overview: getting-started/overview.md
        - Writing a script: getting-started/script.md
        - Syntax tree queries: getting-started/treesitter.md
        - Command line interface: getting-started/cli.md
        - User interface: getting-started/gui.md
    - Contributing:
        - Getting started: contributing/getting-started.md
        - Architecture: contributing/architecture.md
        - Unit tests: contributing/unit-tests.md
    - Script API:
# DO NOT EDIT: THIS IS DONE AUTOMATICALLY
# -->
        - Script Module:
            - Document: API/script/document.md
            - Project: API/script/project.md
            - CppDocument:
                - CppDocument: API/script/cppdocument.md
                - DataExchange: API/script/dataexchange.md
                - DataExchangeEntry: API/script/dataexchangeentry.md
                - MessageMap: API/script/messagemap.md
                - MessageMapEntry: API/script/messagemapentry.md
            - LspDocument:
                - LspDocument: API/script/lspdocument.md
                - ClassSymbol: API/script/classsymbol.md
                - FunctionArgument: API/script/functionargument.md
                - FunctionSymbol: API/script/functionsymbol.md
                - QueryCapture: API/script/querycapture.md
                - QueryMatch: API/script/querymatch.md
                - Symbol: API/script/symbol.md
            - RcDocument:
                - RcDocument: API/script/rcdocument.md
                - Action: API/script/action.md
                - Asset: API/script/asset.md
                - Menu: API/script/menu.md
                - MenuItem: API/script/menuitem.md
                - Shortcut: API/script/shortcut.md
                - String: API/script/string.md
                - ToolBar: API/script/toolbar.md
                - ToolBarItem: API/script/toolbaritem.md
                - Widget: API/script/widget.md
            - TextDocument:
                - TextDocument: API/script/textdocument.md
                - Mark: API/script/mark.md
                - RangeMark: API/script/rangemark.md
                - TextLocation: API/script/textlocation.md
                - TextRange: API/script/textrange.md
            - UiDocument:
                - UiDocument: API/script/uidocument.md
                - UiWidget: API/script/uiwidget.md
            - Items:
                - Script: API/script/script.md
                - ScriptDialog: API/script/scriptdialog.md
            - Utilities:
                - Dir: API/script/dir.md
                - File: API/script/file.md
                - FileInfo: API/script/fileinfo.md
                - Message: API/script/message.md
                - Settings: API/script/settings.md
                - UserDialog: API/script/userdialog.md
                - Utils: API/script/utils.md
                - QDirValueType: API/script/qdirvaluetype.md
                - QFileInfoValueType: API/script/qfileinfovaluetype.md
# <--

markdown_extensions:
    - toc:
        permalink: "#"
        toc_depth: 3
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.tabbed
    - attr_list

plugins:
    - search:
        separator: '[\s\-\.]+'
    - build_plantuml:
          render: "server"
          server: "http://www.plantuml.com/plantuml"
          output_format: "svg"
          diagram_root: "docs/assets"
          output_folder: "."
          input_folder: "."
          input_extensions: ""
