site_name: Knut v4.0

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

use_directory_urls: false

repo_url: https://codereview.kdab.com/admin/repos/knut
repo_name: knut

nav:
    - Home: index.md
    - Contributing: contributing.md
    - API:
        - Script Module:
             - Dir: API/script/dir.md
             - Document: API/script/document.md
             - File: API/script/file.md
             - FileInfo: API/script/fileinfo.md
             - Mark: API/script/mark.md
             - Message: API/script/message.md
             - Project: API/script/project.md
             - QDirValueType: API/script/qdirvaluetype.md
             - QFileInfoValueType: API/script/qfileinfovaluetype.md
             - Script: API/script/script.md
             - Settings: API/script/settings.md
             - TextDocument: API/script/textdocument.md
             - UiDocument: API/script/uidocument.md
             - UiWidget: API/script/uiwidget.md
             - UserDialog: API/script/userdialog.md
             - Utils: API/script/utils.md
        - Script.Mfc Module:
             - Action: API/script.mfc/action.md
             - Asset: API/script.mfc/asset.md
             - Menu: API/script.mfc/menu.md
             - MenuItem: API/script.mfc/menuitem.md
             - RcDocument: API/script.mfc/rcdocument.md
             - Shortcut: API/script.mfc/shortcut.md
             - ToolBar: API/script.mfc/toolbar.md
             - ToolBarItem: API/script.mfc/toolbaritem.md
             - Widget: API/script.mfc/widget.md
        - Script.Test Module:
             - TestCase: API/script.test/testcase.md
             - TestUtil: API/script.test/testutil.md

markdown_extensions:
    - toc:
        permalink: "#"
        toc_depth: 3
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.tabbed
    - attr_list

plugins:
    - search:
        separator: '[\s\-\.]+'
